---
version: '3'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-mysqlfordocker}
      MYSQL_DATABASE: ${DB_NAME:-atlasdb}
      MYSQL_USER: ${DB_USERNAME:-atlas}
      MYSQL_PASSWORD: ${DB_PASSWORD:-iamatlas}
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    healthcheck:
      test: "exit 0"

  atlas:
    image: openmrs/atlas:staging
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_NAME: ${DB_NAME:-atlasdb}
      DB_USERNAME: ${DB_USERNAME:-atlas}
      DB_PASSWORD: ${DB_PASSWORD:-iamatlas}
      LDAP_URI: ${LDAP_URI:-ldaps://ldap-stg.openmrs.org:636}
      LDAP_AUTH_USER: ${LDAP_AUTH_USER:-atlas}
      LDAP_AUTH_PASSWORD: ${LDAP_AUTH_PASSWORD:-magic}
      LDAP_USERS_GROUP: ${LDAP_USERS_GROUP:-atlas-users}
      LDAP_ADMIN_GROUP: ${LDAP_ADMIN_GROUP:-atlas-administrators}
      MAIL_HOST: ${MAIL_HOST:-smtp.mandrillapp.com}
      MAIL_PORT: ${MAIL_PORT:-587}
      MAIL_AUTH: ${MAIL_AUTH:-true}
      MAIL_USER: ${MAIL_USER:-infrastructure@openmrs.org}
      MAIL_PASS: ${MAIL_PASS:-magic}
      GOOGLE_MAPS_JS_API_KEY: ${GOOGLE_MAPS_JS_API_KEY:-XXXXXXXXXXX_XXXXXX-XXXXXXXXXXX-XXXXXXXX}
    ports:
      - 8548:3000
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/markerSites/"]

  backup:
    image: openmrs/cron-backup
    depends_on:
      - db
    volumes:
      - mysql-data:/mysql_data
      - ${BACKUP_DIR-./backups}:/backup
    environment:
      - DIRS=/mysql_data:atlas_mysql
      - SCHEDULE=0 0 * * *
    restart: always
    healthcheck:
      test: "exit 0"

volumes:
  mysql-data:
